### ISSUE TITLE
ArgoCD Helm cannot work

### ISSUE THREAD

**Issue by DuyNT222054M** [argoproj/argo-helm#2019] opened 2023-05-06 18:33 UTC
### Describe the bug

1. Deployment: argo-cd-argocd-server
Pod cannot start with error: **Error: unknown command "/usr/local/bin/argocd-server" for "argocd-server"** 
Maybe change from: 
        _command:
        - argocd-server_
To:
        _args:
        - /usr/local/bin/argocd-server_

2. argocd-dex-server: Crash 
**cp: target '/shared/argocd-dex' is not a directory**

### Related helm chart

argo-cd

### Helm chart version

5.32.0

### To Reproduce

helm install

### Expected behavior

run succcess

**Comment by yu-croco** [comment] 2023-05-07 02:10
Hi @DuyNT222054M , thank you for opening the issue.
Can you please give us your values.yaml?

I tried 2 cases below without customization of values.yaml, but I didn't get the error. 🤔 

- install argo-cd Helm Chart v5.32.0 directly
- install argo-cd Helm Chart v5.24.0 and upgrade to v5.31.0 and v5.32.0

**Comment by xorima** [comment] 2023-05-13 05:26
I am seeing the same issue, so here is my values:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: &ns argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Do after namespace
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.33.2
    helm:
      releaseName: argo-cd
      parameters:
        - name: "configs.cm.url"
          value: "https://mydomain.com"
        - name: "configs.cm.admin\\.enabled"
          value: "false"
        - name: "configs.cm.kustomize\\.buildOptions"
          value: "--enable-helm"
        - name: "configs.params.server\\.insecure"
          value: "true"
        - name: "controller.replicas"
          value: "2"
        - name: "server.replicas"
          value: "2"
        - name: "repoServer.replicas"
          value: "2"
        - name: "controller.metrics.enabled"
          value: "true"
        - name: "controller.metrics.serviceMonitor.enabled"
          value: "true"
        - name: "controller.metrics.serviceMonitor.namespace"
          value: *ns
        - name: "dex.metrics.enabled"
          value: "true"
        - name: "dex.metrics.serviceMonitor.enabled"
          value: "true"
        - name: "dex.metrics.serviceMonitor.namespace"
          value: *ns
        - name: "redis.exporter.enabled"
          value: "true"
        - name: "redis.metrics.enabled"
          value: "true"
        - name: "redis.metrics.serviceMonitor.enabled"
          value: "true"
        - name: "redis.metrics.serviceMonitor.namespace"
          value: *ns
        - name: "server.metrics.enabled"
          value: "true"
        - name: "server.metrics.serviceMonitor.enabled"
          value: "true"
        - name: "server.metrics.serviceMonitor.namespace"
          value: *ns
        - name: "repoServer.metrics.enabled"
          value: "true"
        - name: "repoServer.metrics.serviceMonitor.enabled"
          value: "true"
        - name: "repoServer.metrics.serviceMonitor.namespace"
          value: *ns
        - name: "applicationSet.metrics.enabled"
          value: "true"
        - name: "applicationSet.metrics.serviceMonitor.enabled"
          value: "true"
        - name: "applicationSet.metrics.serviceMonitor.namespace"
          value: *ns
        - name: "notifications.metrics.enabled"
          value: "true"
        - name: "notifications.metrics.serviceMonitor.enabled"
          value: "true"
        - name: "notifications.metrics.serviceMonitor.namespace"
          value: *ns
      values: |
        controller:
          metrics: 
            rules:
              enabled: true
              spec:
                - alert: ArgoAppMissing
                  expr: |
                    absent(argocd_app_info) == 1
                  for: 15m
                  labels:
                    severity: critical
                  annotations:
                    summary: "[Argo CD] No reported applications"
                    description: >
                      Argo CD has not reported any applications data for the past 15 minutes which
                      means that it must be down or not functioning properly.  This needs to be
                      resolved for this cloud to continue to maintain state.
                - alert: ArgoAppNotSynced
                  expr: |
                    argocd_app_info{sync_status!="Synced"} == 1
                  for: 12h
                  labels:
                    severity: warning
                  annotations:
                    summary: "[{{`{{$labels.name}}`}}] Application not synchronized"
                    description: >
                      The application [{{`{{$labels.name}}`}} has not been synchronized for over
                      12 hours which means that the state of this cloud has drifted away from the
                      state inside Git.
        configs:
          cm:
            dex.config: |
              connectors:
                # GitHub example
                - type: github
                  id: github
                  name: GitHub
                  config:
                    clientID: $dexgithubapp:clientID
                    clientSecret: $dexgithubapp:clientSecret
                    orgs:
                    - name: stylelia
              staticClients:
                - id: grafana
                  name: Grafana
                  redirectURIs:
                    - https://mydomain.com/login/generic_oauth
                  secret: $dexgrafanacfg:oAuthSecret
          rbac:
            "policy.csv": |
              p, role:admin, applications, get, */*, allow
              p, role:admin, applications, create, */*, allow
              p, role:admin, applications, update, */*, allow
              p, role:admin, applications, delete, */*, allow
              p, role:admin, applications, sync, */*, allow
              p, role:admin, applications, override, */*, allow
              p, role:admin, applications, rollback, */*, allow
              p, role:admin, applications, resume, */*, allow
              p, role:admin, applications, suspend, */*, allow
              p, role:admin, applications, terminate, */*, allow
              p, role:admin, applications, set, */*, allow
              
              g, org-name:cluster-admins, role:admin
      # see https://argo-cd.readthedocs.io/en/release-2.1/operator-manual/rbac/ for how to
      # configure RBAC
  destination:
    server: "https://kubernetes.default.svc"
    namespace: *ns
```

On looking into the codebase @yu-croco I think it will be caused by https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/deployment.yaml#L62 though I am not sure what this should be?

**Comment by bikram990** [comment] 2023-05-19 09:36
I was also getting the `cp: target '/shared/argocd-dex' is not a directory` error. While checking I found that the deployment has `command` and `args` both defined the same copy block due to this the copy is failing for dex initContainer. I'd recreate the dex `deployment` to fix this issue.

**Comment by yu-croco** [comment] 2023-05-19 09:56
Thank you for investigating @bikram990 !
I'm looking forward to your PR. 🙏

**Comment by bikram990** [comment] 2023-05-21 10:04
@yu-croco I found this in the dex `deployment` applied to my cluster. The helm chart has only an `args` section.

**Comment by yu-croco** [comment] 2023-05-21 10:35
Thank you for investigating @bikram990 .
Do you want to make PR for it? If not, I will make it.

**Comment by bikram990** [comment] 2023-05-22 06:41
@yu-croco I don't know how to fix this in helm chart.

**Comment by pdrastil** [comment] 2023-05-26 12:28
Resolved via https://github.com/argoproj/argo-helm/pull/2070

**Closed by pdrastil** 2023-05-26 12:28 UTC
Labels: bug, argo-cd
