### ISSUE TITLE
Migrate ARGO chart to HELM 3

### ISSUE THREAD

**Issue by rsecob** [argoproj/argo-helm#201] opened 2020-01-04 23:30 UTC
**Is your feature request related to a problem? Please describe.**
When trying to install argo chart with helm 3, the following error pops up:

`manifest_sorter.go:175: info: skipping unknown hook: "crd-install"`

**Describe the solution you'd like**
Make the chart helm 3 compatible

**Comment by evaneaston** [comment] 2020-01-10 15:39
See issue #196 and pr #198 .

**Comment by seanson** [comment] 2020-01-22 23:22
Closing as duplicate of #196

**Closed by seanson** 2020-01-22 23:22 UTC
Labels: argo, duplicate, enhancement, helm3
