### ISSUE TITLE
Sync issue with argo-cd helm chart 7.4.x

### ISSUE THREAD

**Issue by jascsch** [argoproj/argo-helm#2883] opened 2024-08-16 16:20 UTC
### Describe the bug

There is a sync issue with helm chart version 7.4.x so that apps are stuck in "OutOfSync" status.

### Related helm chart

argo-cd

### Helm chart version

7.4.x

### To Reproduce

use the following manifest and try to sync the dapr app.

```
project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: dapr
syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
ignoreDifferences:
  - kind: Secret
    name: dapr-trust-bundle
    namespace: dapr
    jsonPointers:
      - /data
sources:
  - repoURL: 'https://dapr.github.io/helm-charts/'
    targetRevision: 1.11.1
    helm:
      valueFiles:
        - $values/tools/dapr/values.yaml
      releaseName: dapr
      skipCrds: true
    chart: dapr
  - repoURL: 'https://git.xxx.com/org/gitops-cluster-dev.git'
    targetRevision: HEAD
    ref: values
```

### Expected behavior

The sync status should be "Synced" instead of "OutOfSync"
The sync works perfectly fine with helm chart version 7.3.x

### Screenshots

![image](https://github.com/user-attachments/assets/34ee0514-976a-490e-8544-479c5fef4e7a)

**Comment by yu-croco** [comment] 2024-08-16 23:41
Hi @jascsch , since it's related to Argo CD itself, you can get more help in upstream.

**Comment by jascsch** [comment] 2024-08-19 06:40
I created another git issue for Argo CD itself https://github.com/argoproj/argo-cd/issues/19582

**Comment by mkilchhofer** [comment] 2024-09-30 23:23
Chart version 7.4.0 is the first release of Argo CD 2.12 (.0).

Did you try a newer chart version with a newer appVersion, @jascsch ?

**Comment by jascsch** [comment] 2024-10-01 07:14
Hi @mkilchhofer yes, I already tested the latest release which is v2.12.4+27d1e64
The same issue here.

**Comment by jascsch** [comment] 2024-10-01 07:19
There is a significant sync behavior change between these versions.
It doesn`t matter how often I try to sync the app will always be out of sync.

![image](https://github.com/user-attachments/assets/2c76940e-5a95-4926-810e-eeac820521e9)

**Comment by mkilchhofer** [comment] 2024-10-01 10:06
And what is the diff for this Dapr app? (From the screenshot I see that the "Auto sync is not enabled")

**Comment by jascsch** [comment] 2024-10-01 11:16
It is intended that auto sync is disabled.
![image](https://github.com/user-attachments/assets/066f4e2a-31a9-45cf-9090-832eb43a5af3)

**Comment by mkilchhofer** [comment] 2024-10-01 12:58
Okay but from the screenshot you provided I cannot see a misbehaving of Argo CD.
What is the problem here? I am pretty sure that the halm chart of Dapr is using the non-idempotent function `genPrivateKey`, `genCA` and/or `genSelfSignedCert`:
https://github.com/dapr/dapr/blob/f5443ef6bcdaeaebc32c567a87ca1fc58808a518/charts/dapr/charts/dapr_sidecar_injector/templates/dapr_sidecar_injector_webhook_config.yaml#L9

**Comment by jascsch** [comment] 2024-10-02 06:58
behavior with 7.3.x (v2.11.7+e4a0246)
- the dapr app stays in sync and does not show any diffs

behavior with 7.x.x (v2.12.4+27d1e64)
- the dapr app stays out of sync and always shows a diff

The sync behaves completely differently between these versions and there is no workaround for this case.

**Comment by mkilchhofer** [comment] 2024-10-02 07:43
Did you hit refresh and/or hard refresh with the old version "7.3.x (v2.11.7+e4a0246)"? 

As I already sent you the link to the used `genSelfSignedCert` function within the Dapr helm chart, I can say that this is by design. It might be possible that a minor bit changed in 2.12 but to analyze this, I recommend to file an issue in the upstream repository: https://github.com/argoproj/argo-cd/issues/new/choose

**Comment by jascsch** [comment] 2024-10-02 08:32
I already created an issue in upstream repository:
https://github.com/argoproj/argo-cd/issues/19582

**Comment by mkilchhofer** [comment] 2024-10-02 09:32
Alright, lets close this helm chart issue then :)

**Closed by mkilchhofer** 2024-10-02 09:32 UTC
Labels: bug, argo-cd
