### ISSUE TITLE
argo-cd chart version 6.7.4 missing

### ISSUE THREAD

**Issue by SamuraiPrinciple** [argoproj/argo-helm#2611] opened 2024-03-29 00:31 UTC
### Describe the bug

It seems like the latest published chart for argo-cd (6.7.4) is missing.

### Related helm chart

argo-cd

### Helm chart version

6.7.4 

### To Reproduce

helm repo add argo https://argoproj.github.io/argo-helm
helm search repo argo/argo-cd --versions 

### Expected behavior

To see latest chart version

**Comment by islishude** [comment] 2024-03-29 02:07
I can confirm this.

the 6.7.4 doesn't exist in the index.yaml

https://argoproj.github.io/argo-helm/index.yaml

**Comment by mkilchhofer** [comment] 2024-04-02 14:26
It is fixed now with another chart release.
The GitHub pages deployment failed due to a GitHub issue:
> ![GitHub Action output](https://github.com/argoproj/argo-helm/assets/7290987/2ee5515c-0669-4ebc-a541-a658a49230d6)
> 
> Refs:
> - https://github.com/argoproj/argo-helm/actions/runs/8471302611/job/23210980093
> - https://github.com/argoproj/argo-helm/commit/7b14792a8

Chart has arrived inside the index:
```bash
$ helm search repo argo/argo-cd --versions | grep "6\.7\."
argo/argo-cd    6.7.8           v2.10.5         A Helm chart for Argo CD, a declarative, GitOps...
argo/argo-cd    6.7.7           v2.10.5         A Helm chart for Argo CD, a declarative, GitOps...
argo/argo-cd    6.7.6           v2.10.5         A Helm chart for Argo CD, a declarative, GitOps...
argo/argo-cd    6.7.5           v2.10.5         A Helm chart for Argo CD, a declarative, GitOps...
argo/argo-cd    6.7.4           v2.10.5         A Helm chart for Argo CD, a declarative, GitOps...
argo/argo-cd    6.7.3           v2.10.4         A Helm chart for Argo CD, a declarative, GitOps...
argo/argo-cd    6.7.2           v2.10.3         A Helm chart for Argo CD, a declarative, GitOps...
argo/argo-cd    6.7.1           v2.10.2         A Helm chart for Argo CD, a declarative, GitOps...
argo/argo-cd    6.7.0           v2.10.2         A Helm chart for Argo CD, a declarative, GitOps...
```

**Closed** 2024-04-02 14:27 UTC
Labels: bug, argo-cd
