### ISSUE TITLE
helm delete does not remove CRDs

### ISSUE THREAD

**Issue by davidblum** [argoproj/argo-helm#1195] opened 2022-03-24 19:41 UTC
### Describe the bug

When deleting / uninstalling the helm argo-cd chart, CRD's are not removed.

### Related helm chart

argo-cd

### To Reproduce

Setup and install argocd via helm

`helm repo add argo https://argoproj.github.io/argo-helm`
`helm install argocd argo/argo-cd`

Get argo CRD's from k8s
```
kubeect get crd | grep argo
analysisruns.argoproj.io                                         2022-03-17T23:05:09Z
analysistemplates.argoproj.io                                    2022-03-17T23:05:09Z
applications.argoproj.io                                         2022-03-17T23:00:35Z
applicationsets.argoproj.io                                      2022-03-24T19:29:37Z
appprojects.argoproj.io                                          2022-03-17T23:00:37Z
argocdextensions.argoproj.io                                     2022-03-17T23:00:36Z
clusteranalysistemplates.argoproj.io                             2022-03-17T23:05:09Z
experiments.argoproj.io                                          2022-03-17T23:05:09Z
```

Delete argocd via helm
```
helm delete argocd
release "argocd" uninstalled
```

Check CRD's again
```
❯ k get crd | grep argo
analysisruns.argoproj.io                                         2022-03-17T23:05:09Z
analysistemplates.argoproj.io                                    2022-03-17T23:05:09Z
applications.argoproj.io                                         2022-03-17T23:00:35Z
applicationsets.argoproj.io                                      2022-03-24T19:29:37Z
appprojects.argoproj.io                                          2022-03-17T23:00:37Z
argocdextensions.argoproj.io                                     2022-03-17T23:00:36Z
clusteranalysistemplates.argoproj.io                             2022-03-17T23:05:09Z
experiments.argoproj.io                                          2022-03-17T23:05:09Z
```

### Expected behavior

After argocd is uninstalled, I expect the CRD's to be removed / cleaned up.

### Additional context

This caused me an issue when trying to use the `skipCrds` option in v2.3.2.  

For my case, argo kept throwing errors that this was an unknown option.  The root cause was that the CRD was not being updated.

From this debugging I identified that when you helm delete argo, the CRD's are not cleaned up.

**Comment by davidblum** [comment] 2022-03-24 19:57
The root of this issue appears to be helm: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

Can we turn this into a feature request for documentation or calling out how to upgrade CRD's for new features?

**Comment by mkilchhofer** [comment] 2022-03-28 13:31
This is not a bug. It works exactly how helm handles CRDs. For reference please read:
- https://github.com/helm/community/blob/main/hips/hip-0011.md

**Comment by mkilchhofer** [comment] 2022-05-25 09:33
It's documented now via #1251. Closing this. Feel free to reopen or comment if we need more than that.

**Closed by mkilchhofer** 2022-05-25 09:33 UTC
Labels: argo-cd, documentation
