### ISSUE TITLE
Failed to update to 5.28.3

### ISSUE THREAD

**Issue by OlivierJavaux** [argoproj/argo-helm#1962] opened 2023-04-13 15:48 UTC
### Describe the bug

Hello,

5.28.3 helm chart fails to install.
Problem is in templates/argocd-configs/repository-secret.yaml and templates/argocd-configs/repository-credentials-secret.yaml files.
Please, replace ".Release.Namespace" with "$.Release.Namespace" as we are in range section.

Thanks for your help

### Related helm chart

argo-cd

### Helm chart version

5.28.3

### To Reproduce

1. helm template -f ....

### Expected behavior

helm template is working correctly

**Comment by mkilchhofer** [comment] 2023-04-13 20:13
I think you mean version 5.29.0 as 5.28.3 is not a valid release ;-)

Duplicate of #1961 and will be fixed with PR:
- #1963

**Closed** 2023-04-13 23:44 UTC
Labels: bug, duplicate, argo-cd

**Comment by OlivierJavaux** [comment] 2023-04-14 08:02
You are right, 5.29.0.
Many thanks for the quick fix! (5.29.1 solves the problem)
